### PR TITLE
set `sleep_interval`

### PR DESCRIPTION
**Pull request by flashnuke**
this `sleep_interval` param is set between requests in order to avoid `429` errors

### CODE REVIEW

**Comment by Nv7-GitHub** [comment]
Does this prevent 429s?

**Comment by Themis3000** [comment]
I'm guessing not, but this actually seems like a pretty good idea to help mitigate 429 errors. Making a bunch of requests within a single second is usually a pretty good way to get 429's back pretty quick, so staggering requests is usually a good idea with web scraping. This'd just make it easier to stagger requests if the user chooses to do so.

I haven't tested the code, but I took a look at the diffs and it looks good to me personally.

**Comment by Nv7-GitHub** [comment]
It appears that even if you send one request every min it still causes a 429, would need some research into google's ratelimiting in order to understand how they actually do 429s

**Comment by Themis3000** [comment]
> It appears that even if you send one request every min it still causes a 429, would need some research into google's ratelimiting in order to understand how they actually do 429s

That's a good point, it's possible staggering requests has no significant effect on how long it takes for google to rate limit. That would be a good thing to test. I'm guessing there's not going to be a way to totally avoid 429's but there will be ways to be able to make more requests before encountering a 429 I'm sure.

If I get around to doing some tests in the future I'll update on this thread with my findings.

**Comment by flashnuke** [comment]
It helps reduce 429 errors but doesn't prevent them completely 
An even better approach would be to use a random sleep duration each cycle but that might complicate things a bit for the user

**Comment by thehappydinoa** [comment]
This would help with the 429s but I would also recommend rotating user agents. Also something that would be great is letting the user know when a captcha pops up and providing the link to do the captcha. The reason 429s build up is the number of invalid captchas/spammy like calls.

**Comment by Themis3000** [comment]
I like the idea of user agent rotation too. An easy way to do this would be to use `fake-useragent` https://github.com/hellysmile/fake-useragent. I've used it in the past for scraping and it works pretty well and is very very easy to use. Some sites do however detect user agent rotation, so it would be worth a test before pushing an implementation to see if it makes a difference or not.

**Comment by Nv7-GitHub** [comment]
@flashnuke would you be willing to try this out (also please fetch upstream on your branch)

**Comment by flashnuke** [comment]
@Nv7-GitHub I've performed some tests with random user-agents, 429 are still happening but it seems to me less often
I'm not sure how to accurately measure this but regardless rotating them would be good practice

see the recent commits

**Review by Nv7-GitHub — COMMENTED** [review]
Seems good, I'll make a new release when I add getting the number of hits in `search_advanced`

**Pull request merged**
