### PR TITLE
Add Safe Search

### PR DESCRIPTION
**Pull request by VincentX0905**
If you want to turn off the safe search function (this function is on by default), you can do this:
```python
from googlesearch import search
search("Google", safe=None) #turn off safe search
```

If you don't give a safe value, the default is on:
```python
from googlesearch import search
search("Google") #turn on safe search
```

### CODE REVIEW

**Comment by VincentX0905** [comment]
before merging
You can run `pip install -U git+https://github.com/VincentX0905/googlesearch.git` to install the package with safe search option.

**Review by Nv7-GitHub — APPROVED** [review]
Looks good! I will try to take a look at this over my break

**Comment by VincentX0905** [comment]
If you include `&safe="active"` in the URL
SafeSearch mode will be turned on

If `&safe=off` is included in the URL or not specified
SafeSearch mode will be turned off

Google is committed to creating a safe browsing environment
For this reason, I set this feature to be on by default.

**Review by Nv7-GitHub — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
