### PR TITLE
Added the support for proxies

### PR DESCRIPTION
**Pull request by Mohammed-Ashour**
Added Support for adding a proxy to your search 

```python3
from googlesearch import search
proxy = "http://admin:something:someproxy@123.45.678.90:1234"
results = search("github", proxy=proxy)
```

### CODE REVIEW

**Comment by Nv7-GitHub** [comment]
Do you know any proxies to test this on?

**Comment by Mohammed-Ashour** [comment]
Just  added dynamic support for both http and https proxies depends on the users input
you can try this one 
```
http://pubproxy.com/api/proxy
```
```python3
from googlesearch import search
proxy = "http://pubproxy.com/api/proxy"
results = search("github", proxy=proxy)
```

**Comment by Nv7-GitHub** [comment]
Great! I'll check it out soon!

**Comment by Nv7-GitHub** [comment]
Seems to work, I'll merge it!

**Pull request merged**
