### PR TITLE
Added SSL_VERIFY flag

### PR DESCRIPTION
**Pull request by mukthy**
Added SSL_VERIFY flag as with some of the proxy providers it throws SSL errors like below:

(Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129)')))

This flag will take "True" or "False" or path-to-ca.crt file.

It also helps in not installing and configuring the Proxy CA cert for each proxy provider every time in case of planning to use a proxy provider temporarily.

### CODE REVIEW

**Comment by Nv7-GitHub** [comment]
Can you add an example to the README?

**Comment by mukthy** [comment]
@Nv7-GitHub I have added an example in README. Please check: https://github.com/Nv7-GitHub/googlesearch/pull/67

**Comment by Nv7-GitHub** [comment]
I'll take a look at it in April!

**Comment by nicolaswehmeyer** [comment]
> I'll take a look at it in April!

Thanks @Nv7-GitHub - that’s highly appreciated!!

**Review by Nv7-GitHub — APPROVED** [review]
Thanks for the PR!

**Pull request merged**
