### PR TITLE
Search result number as argument

### PR DESCRIPTION
**Pull request by oskarsoderbom**
The start of the search results changed, from hard coded to an argument (default value = 0).

### CODE REVIEW

**Review by Nv7-GitHub — CHANGES_REQUESTED** [review]
Could you add documentation for this in the README?

**Comment by oskarsoderbom** [comment]
> Could you add documentation for this in the README?

Added info in the README.

**Comment by Nv7-GitHub** [comment]
Could you also resolve the conflicts? Thanks!

**Comment by oskarsoderbom** [comment]
Conflicts resolved!

**Review by Nv7-GitHub — APPROVED** [review]
Looks good! It will be part of the next update.

**Pull request merged**
