### PR TITLE
Adding support for pagination. Refactoring code.

### PR DESCRIPTION
**Pull request by carlosplanchon**
I added support for pagination.
Please review the code, because I made a change to the parameters of search()

By the way, useful library!

### CODE REVIEW

**Comment by Nv7-GitHub** [comment]
Wow! Great to see that people are actually improving this bit of code I just decided to make a Python Package on into something that is well structured, has type annotations, and more features! 

I noticed a couple of issues:
- The list type annotation wasn't working for me. I had to add `from typing import List` to the imports and change `list[str]` to `List[str]` to get it working.
- It prints - is it supposed to do that or was that just for debugging?
- It seems to send a lot of requests with the default parameters. After running it twice, I got rate limited by google and changing the User-Agent didn't work.

I wanted to do some more testing, but I got rate limited, I will test some more once Google lets me send requests again. In the meantime, maybe look into these errors? Is there something wrong on my side?

**Comment by carlosplanchon** [comment]
The documentation: That was a mistyping.
The list type annotation: That was because I used Python 3.9+ annotations format.
Prints: Yea, that was for debugging...
About the user-agent problem... Google has very sophisticated systems to detect bots, requests throttling for responsible scraping may be the answer (introducing random sleeps between requests).
Merge this PR, and I'll send you another one with that problems fixed.

**Comment by Nv7-GitHub** [comment]
Looks like there are still a few bugs with the List - in the `Page` class, it still uses a lowercase list, and in the `_search` function, you are using an uppercase list instead of the lowercase one. Other than that, everything works, the Documentation looks great now!

Another thing - This one seems to be quite a bit slower, it appears to be sending 2 requests where the old one sends one. I called the search function with both old and new and timed it. The old one returned 79 results in 1.14 seconds, sending one request. For the new one, I added a print on every request. This one returned 100 results in 18 seconds, sending 20 requests. I did not change any of the parameters, is there a reason it sends so many requests? 18 seconds is quite a bit

**Comment by carlosplanchon** [comment]
```
from googlesearch import search

search(term="term", results_per_page=100, num_results=500)
```
If you use it that way it should send 5 requests and return ~500 results. If num_results = -1 it will try to go to the end of the Google Search pages.

**Comment by Nv7-GitHub** [comment]
Sorry, I didn’t get any emails from GitHub, I will look into this update

**Comment by Nv7-GitHub** [comment]
How many requests does putting in no parameters send?

**Comment by carlosplanchon** [comment]
One request per page of results.

**Comment by Nv7-GitHub** [comment]
So doing `search("Google")` sends only 1 request?

**Comment by carlosplanchon** [comment]
search("Google") sends 1 requests per page of results. If there are 2000 results and you are getting 100 results per page, it should end up doing 20 requests.

**Comment by Nv7-GitHub** [comment]
but, by default, how many pages does it do?

**Comment by carlosplanchon** [comment]
Assuming the scraper is not blocked by Google, by default it will do num_results / results_per_page results, or less if the number of total results in Google is lower.

**Comment by Nv7-GitHub** [comment]
Yes, but what is the default `num_results` and `results_per_page`? When you don't pass any parameters?

**Comment by carlosplanchon** [comment]
def search(term, results_per_page=100, num_results=100, lang="en"):
By default results_per_page=100 and num_results=100

**Comment by Nv7-GitHub** [comment]
Looking much better, I finally got a working environment set up! However, still a few things that need changing
- Why is the bs4 parser being used `lxml`? It requires installing `lxml` and is C dependent (and it isn't in requirements.txt), but when I changed it to `html.parser` it still worked, so I think it should be ok to use `html.parser`

Also, it's much better than before, but it is still sending 3 requests when I use the code 
```python
from googlesearch import search
print(search("Python"))
```

Maybe the logic for checking if its done is broken? Looking great though, hopefully will be merged soon!

**Comment by carlosplanchon** [comment]
lxml is faster than html.parser, but if you want to remove one dependency, that's good too.

**Comment by Nv7-GitHub** [comment]
Any idea why it's still sending 3 requests for the default search?

**Comment by carlosplanchon** [comment]
`cond = self.start < self.num_results`
Thats the stopping condition.

I recommend you to read and practice with Iteration Patterns:
https://python-patterns.guide/gang-of-four/iterator/

That's the way I implemented the pagination.

**Comment by Nv7-GitHub** [comment]
Implemented pagination and cleaned up the code (somewhat), so I'm going to close this

**Pull request closed without merging**
